name: run-action
run-name: ${{ github.actor }} is running Quarkus via Maven
on:
  workflow_run:
    workflows:
      - learn-github-actions 
    types:
      - completed
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          architecture: x64
          distribution: 'temurin'
          cache: 'maven'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-
      - name: Package
        run: mvn clean install 
      - name: Run # Without timeout
        run: docker build --build-arg JAR_FILE=target/*.jar -t org/acme . && docker run -p 8080:8080 org/acme && code=$?;echo "Code = $code" && exit $code
      - name: Run # We add or so that return code is not none-zero which causes pipeline to fail
        run: timeout 1  docker build --build-arg JAR_FILE=target/*.jar -t org/acme . && docker run -p 8080:8080 org/acme && code=$?;echo "Code = $code" && exit $code



